apiVersion: batch/v1
kind: Job
metadata:
  name: create-pg-backups-bucket
  namespace: minio
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://minio.minio.svc.cluster.local:9000 minioadmin minioadmin123 &&
              mc mb --ignore-existing local/pg-backups
